/*
 * Just Order Api
 *
 * An API to create and retrieve Food items and orders.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: john.doe@somecomp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ItemsApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Create a Food item</remarks>
        /// <param name="body">Request Body for Creating a Food item.</param>
        /// <response code="201">The Food item will be Returned with the generated UUID.</response>
        /// <response code="400">The Submitted Request is Malformed.</response>
        [HttpPost]
        [Route("/VinodhThiagarajan1309/just-orders-api/1.0.0/items")]
        [ValidateModelState]
        [SwaggerOperation("CreateV1Item")]
        [SwaggerResponse(statusCode: 201, type: typeof(Item), description: "The Food item will be Returned with the generated UUID.")]
        [SwaggerResponse(statusCode: 400, type: typeof(BadRequestMadeModel), description: "The Submitted Request is Malformed.")]
        public virtual IActionResult CreateV1Item([FromBody]NewItemRequest body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Item));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(BadRequestMadeModel));
            string exampleJson = null;
            exampleJson = "{\n  \"itemId\" : \"907ca62f-33e0-46fd-aebb-5eb59a2bc379\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Item>(exampleJson)
                        : default(Item);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get 1 item based on a UUID</remarks>
        /// <param name="itemId">The UUID of the Item that needs to be retreived.</param>
        /// <response code="200">A successful retrieval of the Item</response>
        /// <response code="400">The Submitted Request is Malformed.</response>
        [HttpGet]
        [Route("/VinodhThiagarajan1309/just-orders-api/1.0.0/items/{itemId}")]
        [ValidateModelState]
        [SwaggerOperation("GetV1Item")]
        [SwaggerResponse(statusCode: 200, type: typeof(Item), description: "A successful retrieval of the Item")]
        [SwaggerResponse(statusCode: 400, type: typeof(BadRequestMadeModel), description: "The Submitted Request is Malformed.")]
        public virtual IActionResult GetV1Item([FromRoute][Required]string itemId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Item));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(BadRequestMadeModel));
            string exampleJson = null;
            exampleJson = "{\n  \"itemId\" : \"907ca62f-33e0-46fd-aebb-5eb59a2bc379\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Item>(exampleJson)
                        : default(Item);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get the List of Food items from the system.</remarks>
        /// <param name="limit"></param>
        /// <response code="200">The list of recently added food items will be returned.</response>
        /// <response code="400">The Submitted Request is Malformed.</response>
        [HttpGet]
        [Route("/VinodhThiagarajan1309/just-orders-api/1.0.0/items")]
        [ValidateModelState]
        [SwaggerOperation("GetV1ItemList")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Item>), description: "The list of recently added food items will be returned.")]
        [SwaggerResponse(statusCode: 400, type: typeof(BadRequestMadeModel), description: "The Submitted Request is Malformed.")]
        public virtual IActionResult GetV1ItemList([FromQuery][Required()]decimal? limit)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Item>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(BadRequestMadeModel));
            string exampleJson = null;
            exampleJson = "[ {\n  \"itemId\" : \"907ca62f-33e0-46fd-aebb-5eb59a2bc379\"\n}, {\n  \"itemId\" : \"907ca62f-33e0-46fd-aebb-5eb59a2bc379\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Item>>(exampleJson)
                        : default(List<Item>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
